### ISSUE TITLE
Yoyos with collecting causes enchanted books to stack

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Jozufozu/Yoyos#12]
Replication steps:

1. Obtain a yoyo

2. Add the collecting enchantment using an anvil

3. Toss a handful of enchanted books on the ground in one place

4. Use the yoyo to pick up the books

What I expect to happen: Each enchanted book will enter my inventory as a different item stack

What actually happens: The enchanted books will stack

**Comment by TheDeviantCrafter** [comment]
I was able to replicate this with the enchantment and Tinkers' modifier. It also affects enchanted diamond swords, white shulker boxes with different contents, and beds. However, it did not stack blue and white shulker boxes (different block IDs), white and blue carpets (stackable), or white and blue beds (different meta data values).

It would appear that for the bug to occur, the following conditions must be met:

-The items must be unstackable
-The items must share a block ID
-The item must share a meta data value

The NBT data doesn't matter. When they stack, the NBT data of all of the items will be overwritten except one.

**Comment by Jozufozu** [comment]
Fixed in abaca163a18e0e4f98bfdb7ac1425530b62f5e55

It was because I wasn't respecting the items' max stack size.
