### ISSUE TITLE
Feature Request: Hopper upgrade for vanilla

### ISSUE THREAD

**Issue by Landstryder** [Jozufozu/Yoyos#19]
I really love this mod without a doubt. Discovered it while playing Forever Stranded Lost Souls and just fell in love. I love the augment of the hopper when using the tinkers version of the weapon, but I really wish you could apply this augment to the vanilla version of the weapon as well somehow. The main reason I'm asking for this is because I added the mod to my own modpack Atom Smasher, but there is no way I'm going to have Tinkers in my pack (OP, don't fit the theme).

Is there anyway you could see fit to make it possible to add that enhancement for the vanilla versions, like maybe applying a hopper to the yoyo using an anvil?

**Comment by Jozufozu** [comment]
Sorry fro the late reply! And thank you for the kind words (= The enchantment already exists in vanilla! I'm not 100% sure how rare it is off the top of my head, but it's called "Collecting"

**Comment by Landstryder** [comment]
oh man that is wonderful, didn't even realize, thanks so much for the awesome mod!
