### ISSUE TITLE
Yoyo w/ Collecting sometimes making items disappear

### ISSUE THREAD

**Issue by randomlypickedname** [Jozufozu/Yoyos#22]
I wish I knew how to narrow this one down, but I finally got it to happen when I was paying attention with a TiCo yoyo in my offhand. I launched it to collect an item and it disappeared after making the "item pickup" sound, without showing up in my inventory. I've had it happen multiple times, with single and multiple items. Any more info I can help with?

Modpack: SevTech 3.0.6
Yoyo ver: 1.2.2.20

**Comment by Jozufozu** [comment]
I'll be able to look into this when I get home. Also, the item first gets put into the yoyo's own inventory.  Are you sure it's not just on top of your yoyo?

**Comment by randomlypickedname** [comment]
We recently switched off of that modpack so I'll have to confirm with our current one, but I'm sure it wasn't just on top of the yoyo. The yoyo would collect items like it should, and when it returns, it would make the collect sound as if I picked the items up but they don't show up anywhere.

**Comment by Jozufozu** [comment]
Thanks for the info. I'm looking into it.
