### ISSUE TITLE
NPE when a Metamorph Enitity was Hit

### ISSUE THREAD

**Issue by WenXin20** [Jozufozu/Yoyos#27]
Forge v14.23.4.2707-1.12.2
Yoyos v1.2.2.20
[Metamorph](https://minecraft.curseforge.com/projects/metamorph) v1.1.6
I got this NPE when I hit a Metamorph Entity with the Rainbow Yoyo. No crash occurred.
[Latest.log](https://gist.github.com/WenXin20/452396434772feddb9b4a71738204e34)

**Comment by Jozufozu** [comment]
It actually looks like [More Player Models](https://minecraft.curseforge.com/projects/more-player-models) is what's causing the NPE. The mod is closed source, so not sure how much I can do here.

**Comment by WenXin20** [comment]
I went ahead and reported it to that mod as well. Maybe the mod author will take a look at it.
Fixed link: https://www.curseforge.com/minecraft/mc-mods/more-player-models/issues/50
