### ISSUE TITLE
Crash when Throwing yoyo (specifically tinkers ones)

### ISSUE THREAD

**Issue by Pyrallux** [Jozufozu/Yoyos#39]

**Comment by kohlth** [comment]
crash log?

**Comment by Pyrallux** [comment]
[crash-2019-07-24_09.57.40-client.txt](https://github.com/Jozufozu/Yoyos/files/3429699/crash-2019-07-24_09.57.40-client.txt)
i think this one is it

**Comment by Jozufozu** [comment]
This is not an issue on the latest version of tinkers' construct. It can be solved by updating
