### ISSUE TITLE
Strange Crash with Yoyos I think related to cord rendering.

### ISSUE THREAD

**Issue by SirAron111** [Jozufozu/Yoyos#41]
https://pastebin.com/pzZkk0zA

Strange Crash with Yoyos I think related to cord rendering.

I think its related to the cord at least it shows this in the crash log

Forge: 14.23.5.2838
Yoyos: yoyos_1.12.2-1.3.3.24.jar

**Comment by Jozufozu** [comment]
Should be fixed in the 1.3.3.25
