### ISSUE TITLE
Yoyos become invisible

### ISSUE THREAD

**Issue by halsaegusa** [Jozufozu/Yoyos#43]
## Bug Report
Yoyos, becoming invisible.

## Steps to Reproduce (for bugs)
1.Play on server.
2.Craft a Yoyo, offhand empty, use it with main hand, 
3.The Yoyo becomes invisible, however, can attack.

btw, I cannot use yoyo with offhand, something with mainhand.
and, if main hand empty, I can use yoyo with offhand, but it becomes invisible.
and, if something with offhand, I can use yoyo.

## Client Information
* forge-14.23.5.2838
* yoyos_1.12.2-1.3.0.21.jar

**Comment by Jozufozu** [comment]
This is related to an issue already fixed in the latest version
