### ISSUE TITLE
No Such Method 1.14.4

### ISSUE THREAD

**Issue by ASpieler** [Jozufozu/Yoyos#45]
Server-side crash
Minecraft: 1.14.4
Forge: 28.0.55
yoyos: 2.0.0.1

I'm almost certain that pose data and animations are client-side only...
one of my players tried to use his yoyo for the first time since the server started up and this happened.

relevant log portion:
```
java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerEntity.func_213307_e(Lnet/minecraft/entity/Pose;)F
	at com.jozufozu.yoyos.common.YoyoEntity.getPlayerHandPos(YoyoEntity.kt:248) ~[?:2.0.0.1] {}
```
full crashlog:
[https://pastebin.com/pgpp9Fs6](https://pastebin.com/pgpp9Fs6)

**Comment by Jozufozu** [comment]
Should be fixed in [this update](https://www.curseforge.com/minecraft/mc-mods/yoyos/files/2779247).

Sorry for the inconvenience!
