### ISSUE TITLE
When using Enchanting Table with Yoyos in hand...

### ISSUE THREAD

**Issue by Snownee** [Jozufozu/Yoyos#8]
When using Enchanting Table with Yoyo in hand, will throw yoyo and cannot look up items' descriptions.

**Comment by Jozufozu** [comment]
I'm not sure what you mean by "cannot look up items' descriptions."
Also, I can open enchanting tables just fine with a yoyo in my hand, what version of the mod are you using?

**Comment by Snownee** [comment]
![image](https://user-images.githubusercontent.com/16059084/34372876-af948798-eb12-11e7-8ac5-3c0dc91f3c7b.png)
Yoyo not in hand, when cursor hovered, show description

![image](https://user-images.githubusercontent.com/16059084/34372929-0cea4112-eb13-11e7-905f-0b5d95080ab2.png)
Yoyo in hand, show nothing

![image](https://user-images.githubusercontent.com/16059084/34372944-2a843f16-eb13-11e7-901a-b281327290b8.png)
Yoyo is thrown at the same time, but in fact I only want to use enchanting table. Also I tested FIshing Rod, sadly has the same problem. So its not a Issue caused by Yoyos.
