### ISSUE TITLE
Iron YoYo damage 

### ISSUE THREAD

**Issue by Mattabase** [Jozufozu/Yoyos#9]
When using the Tinkers YoYo the damage for iron is oddly high. I assume that is a mistake.

https://goo.gl/8A8koW

**Comment by WeaselOnaStick** [comment]
it's odd how different the damage between iron yoyo from the mod and yoyo made with iron TiC parts.

**Comment by AceologyGaming** [comment]
@SHIuSH that always happens w/TCon, compare a TCon stone pick vs vanilla.

**Comment by S-Menz** [comment]
I figure this is because the attack of the iron yoyo body is implemented as 40 instead of 4.0 by mistake.

**Comment by kragnoth** [comment]
The iron.json has the wrong attack value.  Yeah I definitely doubt its meant to have 40.0 instead of 4.0.

**Comment by TheTurkeyDev** [comment]
It's also been pointed out to me that you can manually fix this as well. If you go into the yoyo's config, there's an option where "If enabled, saves materials into a config folder.", "Allows for editing, addition, and removal of stats for yoyos". If you set this to true, then what i believe happens is that the mod will create a yoyos config folder in the configs and then inside that will be all of the yoyo materials. From there you should be able to edit the iron.json file and adjust the value to your liking as well.
